name: Membership

on:
  schedule:
    # Run twice a day at 12pm UTC (8am EST) and 12am UTC (8pm EST)
    - cron: '0 12 * * *'
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update the collection
        run: node ./scripts/get-collection.js

      - name: Generate the members list
        run: yarn generate-members

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: ':bento: feat: updated member list'
          add: 'src/assets/json/*.json'
          push: true